version: '3.8'

services:
  db:
    container_name: db_market
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mercadinho_db
    ports:
      - "5432:5432"
  api:
    container_name: GueguelasMarket
    image: gueguelas
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"